### ISSUE TITLE
chore: add stream key support

### ISSUE THREAD

**Issue by ssddOnTop** [algora-io/tv#41]
I'd like to set a password (aka stream key), to avoid access to bad actors.

Suggestion:
1. allow us to set a custom password
2. autogenerate password and add a button to generate a  new password

**Comment by zcesur** [comment]
Thanks for the suggestion!

Let's split up Stream URL into RTMP URL + Stream key and add reset & copy buttons

RTMP URL without a path is likely invalid so we probably also need to append an arbitrary path like /live (so the RTMP URL becomes rtmp://tv.algora.io:9006/live)

Make sure the change is backward compatible such that someone without a stream key inputted into OBS can continue streaming. That'll involve updating the `Algora.Pipeline.MessageValidator.validate_connect` logic

To reset the key you can use the existing `Algora.Accounts.gen_stream_key` function

<img src="https://github.com/user-attachments/assets/812b113f-d8c3-40c1-bcc2-339142f83235" width="600" />

/bounty $75

**Comment by lastcanal** [comment]
It looks like the `Connect` validator message has the `app` parameter with the url based stream key, while the `ReleaseStream` message has the real `stream_key` parameter. In order to support both we will need to coordinate stream key acceptance in the Pipeline. This will prevent double initializing forwarded RTMP connections, etc. and allow the graceful shutdown of the Pipeline on invalid stream keys.

My plan is to move all the [setup logic](https://github.com/algora-io/tv/blob/main/lib/algora/pipeline/validator.ex#L8-L47) from the Validator into the Pipeline and GenServer call into the pipeline from the validator on both the `Connect` and `ReleaseStream` message. I am hoping to delay calling `Library.init_livestream!` until after the stream is validated, preventing any DB writes before authentication.  Also, in order to implement #73 we will need to connect a user to the pipeline before a new video is created or any HLS outputs are connected. This can be accomplished by switching to `Tee.Parallel` and delaying the creation of the HLS child until the stream is validated, all while removing the need to [pass `video_id`](https://github.com/algora-io/tv/blob/main/lib/algora/pipeline.ex#L24) to the validator.

/attempt #41

**Comment by zcesur** [comment]
Sounds great, LFG

**Comment by zcesur** [comment]
Sounds great, LFG!
