### ISSUE TITLE
Fix LL-HLS playback issue

### ISSUE THREAD

**Issue by zcesur** [algora-io/tv#91]
We currently use HLS to deliver livestreams and VODs to users, which works fine on most devices and browsers. We also implemented LL-HLS delivery (#60), but it doesn't work in some cases. We found out that:

- If we use video.js, it works everywhere except iOS
- If we use vidstack, it works on all devices including iOS, but the playback buffers a lot

Ideally we would make it work with Vidstack so we can switch to that as our default player

Here's a matrix of all player/delivery configurations we have right now:

| Branch         | Player   | Delivery |
| -------------- | -------- | -------- |
| main           | video.js | HLS      |
| ll-hls         | video.js | LL-HLS   |
| vidstack       | vidstack | HLS      |
| vidstack-llhls | vidstack | LL-HLS   |

## Steps to Reproduce

1. Check out one of the LL-HLS branches above
2. Set up and run the development server
3. Paste your RTMP URL from settings into OBS and start streaming
4. Navigate to your stream on an iOS device

## Useful Links

- [videojs/video.js: Video.js - open source HTML5 video player](https://github.com/videojs/video.js)
- [videojs/http-streaming: HLS, DASH, and future HTTP streaming protocols library for video.js](https://github.com/videojs/http-streaming)
- [vidstack/player: Vidstack Player](https://github.com/vidstack/player)
- [Enabling Low-Latency HTTP Live Streaming (HLS) | Apple Developer Documentation](https://developer.apple.com/documentation/http-live-streaming/enabling-low-latency-http-live-streaming-hls)

**Comment by lastcanal** [comment]
I believe the issue is that video.js supports [X-PRELOAD-HINT](https://developer.apple.com/documentation/http-live-streaming/enabling-low-latency-http-live-streaming-hls#Utilize-New-Media-Playlist-Tags-for-Low-Latency-HLS) while HLS.js (via Vidstack) does not, as least not yet. Luckily the amazing devs over at HLS.js have a [feature/preload_hint](https://github.com/video-dev/hls.js/tree/feature/preload-hint) branch that implements it. This could be why Vidstack is stalling while Video.js is not.

Currently none of the `X-PRELOAD-HINT` code that [holds requests open](https://github.com/algora-io/tv/blob/vidstack-llhls/lib/algora/pipeline/hls/ll_controller.ex#L202-L210) until the future 'preloaded' [new segment is ready](https://github.com/algora-io/tv/blob/vidstack-llhls/lib/algora/pipeline/hls/ll_controller.ex#L239) is being exercised by Vidstack.

Here is a waterfall from vanilla Vidstack, you'll notice requests for partial segments happen after the manifest response returns. The short ~30ms duration of the requests show the true time to load a segment on my laptop.

![Screenshot from 2024-09-16 21-47-18](https://github.com/user-attachments/assets/d322837c-4909-4f48-90ab-b5a815bd61fe)

With the `feature/preload_hint` branch you'll notice that requests for the next segment are concurrent with requests for the new manifest and the 'future' segment is able to be downloaded before the new manifest even ready.

![Screenshot from 2024-09-16 21-46-16](https://github.com/user-attachments/assets/054f258b-f7f2-4887-a1da-02601077899a)

I have a PR ready with this very small change, but the ultimate solution to combat stalls is to implement multiple bitrates by transcoding using the [Membrane FFmpeg SWScale plugin](https://github.com/membraneframework/membrane_ffmpeg_swscale_plugin?tab=readme-ov-file). Hopefully this change makes it possible to use Vidstack because it's quite nice!

/attempt #91
